APP_NAME="semantic-match"
APP_VERSION="0.1"


FILE_ALLOWED_TYPES=["text/plain","application/pdf"]
FILE_MAX_SIZE=10

FILE_DEFAULT_CHUNK_SIZE=512000 #3512KB



#======================= LLM Config ==========================
GENERATION_BACKEND="OPENAI"
EMBEDDING_BACKEND="SENTENCE_TRANSFORMER"


EMBEDDING_BACKEND="SENTENCE_TRANSFORMER"
EMBEDDING_MODEL_ID="all-mpnet-base-v2"
EMBEDDING_MODEL_SIZE=768

OPENAI_API_KEY=""
OPENAI_API_URL="https://api.groq.com/openai/v1"
GENERATION_MODEL_ID="llama-3.3-70b-versatile"



INPUT_DAFAULT_MAX_CHARACTERS=1000
GENERATION_DAFAULT_MAX_TOKENS=4000
GENERATION_DAFAULT_TEMPERATURE=0.1

#======================= Vector DB Config ==========================
VECTOR_DB_BACKEND="QDRANT"
VECTOR_DB_HOST="qdrant"
VECTOR_DB_PORT=6333
VECTOR_DB_DISTANCE_METHOD="cosine"


